
# website settings
website:
  title: "Scott Oatley"                                # My name
  description: "PhD Student in Sociology"   # My Title
  image: img/profile.jpeg
  
  # start of the navigation bar at the top of the website
  navbar:
    pinned: true
    
    # My sub-pages
    left:
      - text: "Presentations"
        href: presentations/index.qmd
      - text: "Training"
        href: training/index.qmd
      - text: "Projects"
        href: projects/index.qmd   
      - text: "Teaching"
        href: teaching/index.qmd  
      - text: "CV"
        href: cv/index.qmd   
  
    # My social media handles
    right:
      - icon: GitHub
        href: https://github.com/Scott0atley
      - icon: twitter
        href: https://twitter.com/Scott_Oatley_
      - icon: linkedin
        href: https://www.linkedin.com/in/scott-oatley-b87408157/
      - icon: envelope
        aria-label: email
        href: "mailto:mail.s2265605@ed.ac.uk"  
  
  
  search: 
    location: navbar
    type: textbox

project:
  type: website
  output-dir: docs

  preview: 
    port: 22222
    browser: true
    watch-inputs: true
    navigate: true

execute:
  freeze: true

format:
  html:
    fontsize: 1.1em
    theme: 
      - cosmo
    toc: false
    code-link: true
    anchor-sections: true
    fig-cap-location: margin
    reference-location: margin
    footnotes-hover: true
