---
title: "Teaching"
format: 
  html:
    toc: true
    toc-title: "On This Page"
    number-sections: false
    self-contained: true
    code-fold: true

---
      
# Teaching
  
Here is a list of my courses I have previously taught, or currently teach on:
      
## Introduction to Political Data Analysis: PLIT08009
  
  **Description:**  
This Year 2 course will introduce students to political data analysis using domestic and international data. 

  **Date:** 2025, Semester 2
  
[Course Catalogue](http://www.drps.ed.ac.uk/16-17/dpt/cxplit08009.htm)
    
  ---
      
## History of Western Medicine: STIS08009
  
  **Description:**  
A general introduction to the history of medicine in Western society from the Ancient Greeks to the present. 

  **Date:** 2024, Semester 1
  
[Course Catalogue](http://www.drps.ed.ac.uk/20-21/dpt/cxstis08009.htm)
  
  ---
  
## Mathematics for Social Science: SSPS08009
  
  **Description:**  
This course aims to provide students in the with Quantitative Methods programmes with the mathematical foundations, which will allow them to fully explore advanced methods, as well as gain a full understanding of the mathematic principles behind the basic methods. Throughout the course, the application of mathematics to social science research problems will be emphasised. 

  **Date:** 2024, Semester 1
  
[Course Catalogue](http://www.drps.ed.ac.uk/15-16/dpt/cxssps08009.htm)

  ---
  
## Doing Survey Research: SCIL10063
  
  **Description:**  
This course is designed to meet the needs of those students who want to develop their knowledge of survey methods, introductory statistics and quantitative data analysis. 

  **Date:** 2024, Semester 2 & 2022, Semester 2
  
[Course Catalogue](http://www.drps.ed.ac.uk/17-18/dpt/cxscil10063.htm)

  ---      

## Empires: SCAN08010
  
  **Description:**  
The course will introduce students to classic themes and concepts in colonial studies, post-colonial studies, cultural studies and political economy, through accounts of cultural, political and economic change in the social anthropology of Africa, Latin America, South Asia and the Pacific. 

  **Date:** 2023, Semester 2 
  
[Course Catalogue](http://www.drps.ed.ac.uk/16-17/dpt/cxscan08010.htm)

  ---    
      
## Intimate Relationships: SCIL10023
  
  **Description:**  
The course explores different sociological understandings of such relationships and debates about the nature of social change in personal life. 

  **Date:** 2023, Semester 2 
  
[Course Catalogue](http://www.drps.ed.ac.uk/20-21/dpt/cxscil10023.htm)

  ---   
      
## Sociology 1A: The Sociological Imagination: Individuals and Society: SCIL08004
  
  **Description:**  
This course introduces some of the key ideas of the discipline by examining the relationship between 'individuals' and 'societies'. Among the topics will be the social nature of the self, the influence of groups, gender identities, nationalism and the city.

  **Date:** 2023, Semester 1 
  
[Course Catalogue](http://www.drps.ed.ac.uk/16-17/dpt/cxscil08004.htm)

  ---    

## Longitudinal Data Analysis: PGSP11487
  
  **Description:**  
This course is designed to introduce students to a variety of statistical approaches to analyzing longitudinal data. The course will have a practical focus and introduce students to analyzing existing large-scale household panel datasets. These datasets will include the British Household Panel Survey and Understanding Society (the UK Household Longitudinal Survey). The course will be taught using Stata software.

  **Date:** 2022, Semester 2 
  
[Course Catalogue](http://www.drps.ed.ac.uk/20-21/dpt/cxpgsp11487.htm)

  ---   
