---
title: "Training"
format:
  html:
    toc: true
    toc-title: "On This Page"
    number-sections: false
    self-contained: true
    code-fold: true
---

Here is a list of training sessions, workshops, or courses I have delivered or attended:

---

## Survey and Questionnaire Construction: the Shiny Package in R

**Type:** Workshop Delivered  
**Date:** November 24th 2024  
**Location:** Edinburgh Futures Institute, Edinburgh, Scotland  

Description: This training event will cover teaching users about the Shiny package within the R environment. The Shiny package allows users to create their own applications free of charge and host them online. This training will focus on a key aspect of app creation – creating one’s own survey/questionnaire that can be used in their own research agenda.

- [View Training Materials](shinytrainingblog.pdf){target="_blank"}  
- [View Example Code #1](examplecode1_SO_21112024.R){target="_blank"}  
- [View Example Code #2](examplecode2_SO_21112024.R){target="_blank"}  
- [View Example Code #3](examplecode3_SO_21112024.R){target="_blank"}  
- [View Example Code #4](examplecode4_SO_21112024.R){target="_blank"}  
- [View Example Code #5](examplecode5_SO_22112024.R){target="_blank"}  
- [View Example Code #6](examplecode6_SO_22112024.R){target="_blank"}  
- [View Example Code #7](examplecode7_SO_22112024.R){target="_blank"}  
- [View Example Code #8](examplecode8_SO_22112024.R){target="_blank"}  
- [View PowerPoint](shinytraining.pptx){target="_blank"}

---

## Jupyter Notebook: Improving Workflow for Social Science Research

**Type:** Workshop Delivered  
**Date:** October 20th 2023  
**Location:** Edinburgh, Scotland

Description: This training will focus on setting up Jupyter Notebook on individual devices and importing the user’s data analysis software of choice (course taught in Stata) into the Notebook environment. After setup is complete, training will focus on establishing the various tools that Jupyter Notebook has to offer; demonstrating how Jupyter goes beyond the clunky and sometimes dysfunctional .do files of Stata and other software providers.

- [View Training Materials](shinytrainingblog.pdf){target="_blank"}  
- [View PowerPoint](Jupyter.pptx){target="_blank"}

---

## Introduction to Statistics in Stata

**Type:** Teaching Materials 
**Date:** Jan 1st 2023
**Location:** Edinburgh, Scotland

Description: These files will provide a holistic undergraduate level understanding of quantiative methods. 

- [View Intro to Quantitative Statistics](QuantitativeStatistics.docx){target="_blank"}
- [View Intro to Advanced Quantitative Statistics](AdvancedQuantitativeStatistics .docs){target="_blank"}
- [View Example Dataset](teachingset.dta){target="_blank"}  
- [View Example Code #1](GettingStartedwithStata1.do){target="_blank"}  
- [View Example Code #2](GettingStartedwithStata2.do){target="_blank"}  
- [View Example Code #3](GettingStartedwithStata3.do){target="_blank"}  

---
