---
title: "Presentations"
author: "Scott Oatley"
format:
  html:
    toc: true
    toc-title: "On This Page"
    number-sections: false
    self-contained: true
    code-fold: true
---

# Academic Presentations

Here is a list of academic conference presentations I have delivered:

## Youth in Transition: Longitudinal Comparisons of Youth Transitions in the UK using Cohort and Synthetic Cohort Data

**Conference:** Social Stratification Seminar  
**Date:** 2024 
**Location:** Stirling, Scotland 

[View Slides](presentations/stirling_scott_oatley_20240827.pdf){target="_blank"} 
[View Appendix App](https://scottoatley.shinyapps.io/Youth_In_Transition/)  

---

## How should we handle missing data?

**Conference:** Large Social Survey Symposium 
**Date:** 2024 
**Location:** Stirling, Scotland

[View Slides](presentations/large_surveys_missing_data_02052024.pdf){target="_blank"}

---

## How should we handle missing data?

**Conference:** Large Social Survey Symposium 
**Date:** 2024 
**Location:** Stirling, Scotland

[View Slides](presentations/large_surveys_missing_data_02052024.pdf){target="_blank"}

---

## Using Shiny as a teaching tool? Construction of the GBCS, NS-SEC, and Wright’s Neo-Marxian Schema as an open-source class calculator application

**Conference:** British Journal of Sociology Inaugural Conference
**Date:** 2024  
**Location:** London, UK  

[View Slides](presentations/BJS_Conference_Shiny_13042024.pdf){target="_blank"} 

---

---

## Youth Transitions and Economic Activity: A Re-examination of NCDS data

**Conference:** New Directions  
**Date:** 2023  
**Location:** Edinburgh, Scotland

[View Slides](presentations/qstep_18022024.pdf){target="_blank"} 

---

